In [132]:
import pandas as pd
import numpy as np

____________________________________________________________
**Generated an array of zeroes using inbuilt numpy function**
____________________________________________________________

In [138]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


_______________________________________________________________________
**Did run the given code and found the dot product of both arrays**
_______________________________________________________________________

In [139]:
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[6 6 2 2]
 [3 5 7 5]
 [6 9 3 3]]
[[6 4 7]
 [2 5 5]
 [8 2 9]
 [7 4 2]]


In [140]:
a.dot(b)

array([[ 78,  66,  94],
       [119,  71, 119],
       [ 99,  87, 120]])

In [141]:
print(np.dot(a, b))

[[ 78  66  94]
 [119  71 119]
 [ 99  87 120]]


In [142]:
b.dot(a)

array([[ 90, 119,  61,  53],
       [ 57,  82,  54,  44],
       [108, 139,  57,  53],
       [ 66,  80,  48,  40]])

In [143]:
print(np.dot(b, a))

[[ 90 119  61  53]
 [ 57  82  54  44]
 [108 139  57  53]
 [ 66  80  48  40]]


In [144]:
p1 = np.dot(a, b)
p2 = np.dot(b, a)
p1.shape
p2.shape

(4, 4)

_______________________________________________________________________________
**Read the CSV file provided using Pandas and displaying the first 5 entries**
_______________________________________________________________________________

In [145]:
dataset = pd.read_csv('data.csv')

In [146]:
dataset.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

_______________________________________________________________________________
**Described the data with all features**
_______________________________________________________________________________

In [147]:
dataset.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [148]:
dataset.shape

(25, 6)

In [149]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.3+ KB


________________________________________________________________________________
**Found the total count of missing values for each feature**
________________________________________________________________________________

In [150]:
dataset.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

________________________________________________________________________________
**Displayed of all unique values from the 'DESCRIPTION' column**
________________________________________________________________________________

In [151]:
dataset.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

________________________________________________________________________________
**Created a grouped table using 'DESCRIPTION' as the grouping columns with the means of all the other columns**
________________________________________________________________________________

In [152]:
dataset.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

________________________________________________________________________________
**Generated a random sample of 10 rows from the data**
________________________________________________________________________________

In [153]:
dataset.sample(10)

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
9         30           Fort Mandan State Recreation Area  ...   0.000005   0.009396
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
4         25                   Grahams Island State Park  ...   0.000469   0.125546
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
23        45                      Cross Ranch State Park  ...   0.000274   0.180257
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
10        31                  Little Missouri State Park  ...   0.003136   0.313756

[10 rows x 6 columns]

________________________________________________________________________________
**Added a Feature called 'New_feature' to the new Dataset and Added Random float Values in between 0 and 1 using Numpy**
________________________________________________________________________________

In [154]:
new_dataset=dataset.assign(New_feature=list(np.random.rand(len(dataset))))

In [155]:
new_dataset

OBJECTID  ... New_feature
0         21  ...    0.393062
1         22  ...    0.579708
2         23  ...    0.369747
3         24  ...    0.724366
4         25  ...    0.148859
5         26  ...    0.048245
6         27  ...    0.491824
7         28  ...    0.925108
8         29  ...    0.248087
9         30  ...    0.210965
10        31  ...    0.798885
11        32  ...    0.626915
12        35  ...    0.948499
13        36  ...    0.302578
14        33  ...    0.107694
15        34  ...    0.502232
16        37  ...    0.512453
17        38  ...    0.624851
18        39  ...    0.291946
19        40  ...    0.655202
20        41  ...    0.313984
21        43  ...    0.426121
22        44  ...    0.767945
23        45  ...    0.630454
24        42  ...    0.560155

[25 rows x 7 columns]

________________________________________________________________________________
**Replaced zero value of column 'OBJECTID' with mean value permanently**
________________________________________________________________________________

In [163]:
dataset.OBJECTID.mean()

31.68

In [162]:
dataset[dataset.OBJECTID==33]=0
dataset

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0         21                   Fort Stevenson State Park  ...   0.000284   0.135641
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3         24                      Fort Ransom State Park  ...   0.000444   0.128733
4         25                   Grahams Island State Park  ...   0.000469   0.125546
5         26                        Icelandic State Park  ...   0.000461   0.166712
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
7         28                  Lewis and Clark State Park  ...   0.000256   0.130420
8         29         Lewis and Clark Interpretive Center  ...   0.000007   0.016774
9         30           Fort Mandan State Recreation Area  ...   0.000005   0.009396
10        31                  Little Missouri State Park  ...   0.003136   0.313756
11        32                      Sully Creek State Park  ...   0.000030   0.024016
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
14         0                                           0  ...   0.000000   0.000000
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
20        41           Missouri River State Natural Area  ...   0.000083   0.087192
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
23        45                      Cross Ranch State Park  ...   0.000274   0.180257
24        42         Pelican Point State Recreation Area  ...   0.000013   0.026357

[25 rows x 6 columns]